- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature_request.md
> [Feat]: add issue template

- backend/auth/authMiddleware.js
- backend/controllers/usersControllers.js
- backend/package-lock.json
- backend/package.json
- backend/routes/usersRoutes.js
- backend/server.js
This closes #50 
Ways of Getting Token:
1) Through Cookies
2) Token Passed in headers
Testing Screenshot:
Using Token [Authorization]
Without Using Token [Token accessed through cookies]
> Middleware and Protected Routes Implemented

- frontend/src/navigations/StackNavigation.js
- frontend/src/screens/SplashScreen.jsx
This PR addresses issue [#30](https://github.com/SB2318/UltimateHealth/issues/30)
I have added the splash screen into the application.
> Design a SplashScreen and Integrate it with the project (Implement Stack Navigation) #30

- frontend/App.tsx
- frontend/src/helper/Metric.ts
- frontend/src/screens/HomeScreen.tsx
- frontend/src/screens/auth/LoginScreen.tsx
ISSUE ID : [#48](https://github.com/SB2318/UltimateHealth/issues/48)
**Here is the preview of login page in ios with dark mode and light mode** 
**Here is the preview of login page in android with dark mode and light mode**
> Design Login Screen

- .github/workflows/close-on-merge.yml
Fixes #68 
@SB2318 please review and merge this PR
> added the workflow as mentioned in issue #68

- .github/workflows/autocomment-iss-close.yml
- .github/workflows/close-on-merge.yml
Fixes #70 
@SB2318 please review and merge this PR
> added remaining workflows

- README.md
- backend/README.md
This Closes #55 
Readme for backend successfully done with proper instructions
> Readme.md set for the Backend Setup

- README.md
- backend/package-lock.json
- backend/package.json
- frontend/App.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/src/navigations/StackNavigation.js
- frontend/src/screens/SplashScreen.jsx
- frontend/src/screens/StorageUtils.jsx
- frontend/src/screens/auth/LoginScreen.tsx
fixes issue #63 
I have added Storage util.js  which has function for retrieving data from asyncStorage.
changed onclick function on login button in loginScreen.tsx
added check for user login at splashscreen.jsx.
- [X ] New feature (change which adds functionality)
- [] Frontend
#63
> Added Restriction For Navigation Between SplashScreen and LoginScreen #63

- README.md
Added Contributor Code History, Tech Stack Logos, Number of Forks, Number of PRs, Last Commit
Fixes: #103 
https://github.com/SB2318/UltimateHealth/assets/125258286/fda7e247-3cdf-4d4c-8c4d-3e43b3f0a3f6
#103
> Updated readme.md ( Added Contributor Code History, Tech Stack Logos, Number of Forks, Number of PRs, Last Commit)

- README.md
Added a Header section with links to the different sections of the README file.
1.  Added a Headers section to jump to the sections easily.
2. Case conversion of "last commit" to "Last Commit" for uniformity in the logos.
3. Put a space before the parenthesis of audio features under the **Features:** header. 
4. Pluralized the word _Stack_ in the **Technology Stack** Header.
5. Made the letter _i_ in _installed_ to lowercase under **Project Requirements:** header.
6. Gave links to Oracle java page for better user accessibility.
7. Expanded the short form u into you  and made the letter p into lowercase in the word "**Please**" for sound grammar.
[[Docs]: Enhancement: Add Links to Headers in README File](https://github.com/SB2318/UltimateHealth/issues/94)
📷  Snapshots
1.
2.
3. 
4.
5. 
6. …
> Added Links to the Headings

- frontend/package-lock.json
- frontend/src/screens/auth/LoginScreen.tsx
Added show-hide feature
- [y ] New feature (change which adds functionality)
- [y ] Frontend
closes #77 
- [ y] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [y ] I have optimized the file changes.
- [ y] I have added a snapshot of my work example.
- [ y] I have made a PR to the project's develop branch.
- [ y] My code follows the style guidelines of this project.
- [ y] I have performed a self-review of my code.
- [ y] I have commented my code, particularly in hard-to-understand areas.
- [ y] I have made corresponding changes to the documentation.
- [ y] I have checked for plagiarism and assure its authenticity.
- [ y] I have read and followed the code of …
> 💡[FEATURE]: Add a show-hide feature for the password field in a login page #77

- backend/.env
- backend/auth/authMiddleware.js
- backend/controllers/emailservice.js
- backend/controllers/usersControllers.js
- backend/models/UnverifiedUserModel.js
- backend/models/UserModel.js
- backend/routes/usersRoutes.js
💡[Feature]: Redirect User to home page After Verification Analysis and Possibility measurement. 
-Ensured all the things required in Pr
- [ y] New feature (change which adds functionality)
- [y ] Backend
#closes  #134 
- [y ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [y ] I have optimized the file changes.
- [y ] I have added a snapshot of my work example.
- [y ] I have made a PR to the project's develop branch.
- [ y] My code follows the style guidelines of this project.
- [ y] I have performed a self-review of my code.
- [ y] I have commented my code, particularly in hard-to-understand areas.
- [ y] I have made corresponding changes to the documentation.
- …
> 💡[Feature]: Redirect User to home page After Verification Analysis and Possibility measurement. #134

- backend/models/Articles.js
- backend/package-lock.json
- backend/package.json
- [X ] New feature (change which adds functionality)
- [ X] Backend
#closes
- [X ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X ] I have optimized the file changes.
- [X ] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have made corresponding changes to the documentation.
- [X ] I have checked for plagiarism and assure …
> 💡[FEATURE]: Adding Database model for Articles #57

- backend/controllers/articleController.js
- backend/middleware/authentcatetoken.js
- backend/routes/articleRoutes.js
Added  API for Articles
- [X ] New feature (change which adds functionality)
- [X ] Backend
Create article api working
Get all  articles  api working
backend storage of articles 
Get   articles by Id api working
Update  articles by Id api working
Delete articles by Id api working
#closes
- [ X] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [ X] I have optimized the file changes.
- [ X] I have added a snapshot of my work example.
- [X ] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I …
> 💡[Feature]: Article API creation #156

- backend/controllers/articleController.js
- backend/controllers/usersControllers.js
- backend/models/UserModel.js
- backend/routes/usersRoutes.js
I have created an api for the profile api where the profile of the user can be fetch through the auth token that can be received the the cookies .
I have updated the articles createArticle api where at the time of article creation  the articles field to that user will also be updated according to that .
#closes : #169
> Added Profile Api and update profile with article api 

- backend/controllers/usersControllers.js
- backend/routes/usersRoutes.js
Added Apis to follow and unfollow user only user with token present in authorization or in cookie (Authentcation) can follow or unfollow someone.
if Someone tries to follow some one then in following of user , follower userid will be store and users following count will increase by 1, and follower user case his followers will be increase by one and in followers userid will get stored 
- [ X] New feature (change which adds functionality)
#closes
- [ X] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X ] I have optimized the file changes.
- [ X] I have made a PR to the project's develop branch.
- [X ] My code …
> 💡[Feature]: Follow and Unfollow functionality from backend. #184 

- DataSources/chronic_pain.md
Added Doc about  Chronic Pain 
- [X ] Documentation update
- [X ] Documentation
#closes
- [X ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X ] I have optimized the file changes.
- [ X] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have made corresponding changes to the documentation.
- [ X] I have checked for plagiarism and assure its authenticity.
- [X ] I have read and followed the code of conduct for this …
> 📝[Docs]: Chronic Pain (Long Term) #178

- DataSources/Alzheimer's Disease.md
- DataSources/Hindi/Alzheimer's Disease.md
added documentation on Alzheimer's Diseases #181 
- [X ] Documentation update
- [X ] Documentation
#closes
- [X ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [ X] I have optimized the file changes.
- [X ] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have made corresponding changes to the documentation.
- [X ] I have checked for plagiarism and assure its authenticity.
- [X ] I have read and followed the code of …
> Alzheimer's Diseases: Understanding the Symptoms and Care #181

- backend/controllers/articleController.js
- backend/controllers/usersControllers.js
- backend/models/UserModel.js
- backend/package-lock.json
- backend/package.json
- backend/routes/usersRoutes.js
FIXED ARTICLE CREATION PROBLEM + CREATED API AS IN DESCRIPTION
hey @SB2318 just remeber these 2 paths are query parameter so you can call them like this 
**/collect-monthly-records-for-writing?userId=your_user_id&month=07-2024** 
**/collect-monthly-records-for-reading?userId=your_user_id&month=07-2024**
- [X ] New feature (change which adds functionality)
- [X ] Backend
#closes
- [X ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X ] I have optimized the file changes.
- [X ] I have performed a …
> [Feature]: Implement User Article Engagement (Read & Write Count of articles) (Backend) #200

- frontend/package-lock.json
- frontend/src/helper/APIUtils.ts
- frontend/src/helper/Utils.ts
- frontend/src/screens/HomeScreen.tsx
- frontend/src/type.ts
> Make Categories Dynamic In the Home Page .(Integrate Tag API)

- DataSources/chronic-illness.md
Added Comprehensive topic on - Understanding and Managing Chronic Illness
https://github.com/SB2318/UltimateHealth/issues/231
#closes
Fixes #231 Issue
> Understanding and Managing Chronic Illness

- DataSources/Osteoporosis.md
- DataSources/chronic-illness.md
Added information on the topic - How to Prevent and Treat Osteoporosis
This PR fixes #241 issue
#241 
#closes
> How to Prevent and Treat Osteoporosis

- DataSources/Role of Diet.md
Added information about the topic - Role of Diet in Managing Autoimmune Diseases.
@SB2318, kindly view this PR
Fixes #242 issue
#242 issue closes
> Role of Diet in Managing Autoimmune Diseases

- Learn.md
- README.md
1. The Table of Contents in the Learn.md file have been modified to be links for easy navigation.
2. The Contents of README.md file are updated in accordance with the latest updates.
📷 
- The headers in Learn.md file
- Contents in README.md file
- As Project Requirements have been moved to a drop down, the subheadings are correspondingly listed under the same as listing them with the main contents does not work.
- The same has been done for the Getting Started section where subheadings are listed under the same dropdown because navigation from content under one dropdown to other did not seem to be supported.
#closes  
#176
> Addition and Updating of Links in README.md and Learn.md files

- README.md
I changed  Installation and Setup Guide
- [] Documentation update
- [] Documentation
#closes
- [] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [] I have optimized the file changes.
- [] I have added a snapshot of my work example.
- [] I have made a PR to the project's develop branch.
- [] My code follows the style guidelines of this project.
- [] I have performed a self-review of my code.
- [] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [] I have checked for plagiarism and assure …
> Adding Installation and Setup Guide

- DataSources/Are People Truly Possessed by Ghosts.md
The article explores the topic "Are People Truly Possessed by Ghosts?" by examining the cultural and historical beliefs around possession and correlating these experiences with modern psychological interpretations. Detailed descriptions of mental disorders such as Dissociative Identity Disorder, Psychosis, Schizophrenia, and Conversion Disorder are included to explain possession experiences
#closes
> Added Are People Truly Possessed by Ghosts.md

- DataSources/Assets/Digital-Detox:Balancing_Technology_and_Mental_Health.md
Digital Detox: Balancing Technology and Mental Health
closes #292 
#closes
> Created Digital-Detox:Balancing_Technology_and_Mental_Health.md

- frontend/src/screens/ProfileEditScreen.tsx
#158 
Figma Link : [Filter Page](https://www.figma.com/design/TJ4s3xBpRwoZJCUHzQ2yhY/Filter-Page?node-id=0-1&t=qPkb8Qx6OBz4mHUk-1)
#closes
#158
> Filter Page Design In figma

- DataSources/Leukemia.md
I added brief description on the topic - "Leukemia"
Fixes #307 issue
#307 closes
> Leukemia - Blood Cancer

- DataSources/Thyroid Disorders.md
Added Brief Introduction on the topic - "Thyroid Disorders - Diagnosis and Management"
Fixes #309 isss\ue
Fixes #309 issue
#309 closes
> Thyroid Disorders - Diagnosis and Management

- DataSources/Fasting.md
I added brief introduction on the topic - "Benefits of Intermittent Fasting"
#261 issue is fixed 
#closes
@SB2318, view this PR
> Benefits of Intermittent Fasting

- .github/workflows/pr_greet.yml
pr_greet.yml has been updated. The workflow for commenting on a new pr creation which was earlier is fixed now. A comment will now be made on a new pull request being raised.
Fixes #343 
#closes #343
> Updated pr_greet.yml

- .github/pr-title-checker.json
- .github/workflows/pr-title-checker.yml
Implemented a GitHub Actions workflow to automatically validate the titles of pull requests (PRs) when they are opened, edited, reopened, or synchronized.
Fixes #101 
#closes #101
> PR Title Checker added

- DataSources/Humor and Laughter - Spanish.md
Converted the article Humor and Laughter into Spanish
Fixes #346 
#closes #346
> Created Humor and Laughter - Spanish.md

- DataSources/Assets/Immuno-Boosting Trends: Enhancing Your Body’s Defense System.md
> Create Immuno-Boosting Trends: Enhancing Your Body’s Defense System.md

- .github/workflows/auto-comment-pr-merge.yml
Added the auto-comment-pr-merge.yml file in .github/workflows directory to add the autocommenting feature after merging of pull requests.
Fixes #359 
#closes #359
> Created auto-comment-pr-merge.yml

- DataSources/Neuroplasticity.md
I added brief information on the topic #368 
Fixes #368 issue
#368 closes
> Neuroplasticity.md

- .github/workflows/close-old-issue.yml
- .github/workflows/close-old-pr.yml
- Added workflows for closing old issues and PRs which have been inactive for a span of 30 days
#373 
closes #373
> feat: added workflows: close old issues

- DataSources/English/Plant-based-diets.md
This documentation include the content on The Science Behind Plant-Based Diets
#394
> The Science Behind Plant-Based Diets

- Datasources/stem cell therapy.md
Added Brief Introduction on the topic - "Stem Cell Therapy"
Fixes #369 
#369 closes
@SB2318, view this PR and let me know if you require any modifications.
Or else, kindly merge into main
> Stem cell therapy

- DataSources/French/HIV-French.md
- DataSources/Spanish/HIV-Spanish.md
HIV/AIDS: Understanding and Management converted into French and Spanish 
HIV/AIDS: Understanding and Management converted into French and Spanish .
#336
> HIV/AIDS: Understanding and Management converted into French and Spanish 

- Datasources/Subconscious Brain.md
Power of Subconscious Brain 
Fixes #372 issue
#372
#372closes
> Power of Subconscious Brain.md

- DataSources/English/Immunotherapy-Cancer-Treatment.md
> Article about Advances in Inmmunotherepy for cancer treatment

- DataSources/English/Cluster on Genetic-Diseases.md
> Added document on Genetic diseases prevention and maintenance

- Datasources/Nanotechnology.md
Nanotechnology in Medicine
- [] New feature (change which adds functionality)
#436 issue is fixed
#436 closes
> Nanotechnology in Medicine

- Datasources/Cystic_Fibrosis.md
Added Create Cystic_Fibrosis
#433
> Added Create Cystic_Fibrosis

- Datasources/Hemophilia.md
Added Hemophilia
Fixes #444 issue
#444 closes
@SB2318 view this PR
> Hemophilia

- Datasources/Osteoporosis Overview Strengthening Bones and Preventing Fractures/English.md
> Added "Osteoporosis Overview Strengthening Bones and Preventing Fractures"

- Datasources/Sjögren’s Syndrome Survival Managing Dryness and Fatigue/English.md
> Added "Sjögren’s Syndrome Survival Managing Dryness and Fatigue"

- Datasources/Nanotechnology.md
- Datasources/Thalassemia.md
Added topic - Thalassemia
@SB2318 view this PR
#461 issue
#461 closes
> Thalassemia

- Datasources/Rheumatoid_Arthritis_Malay.md
- Datasources/Rheumatoid_Arthritis_Spanish.md
Converted the article on Rheumatoid Arthritis into Spanish and Malay
Fixes #379 
#closes #379
> Rheumatoid Arthritis (Spanish and Malay)

- Datasources/Obesity.md
Added Obesity information and Preventions
#432
> Added Obesity information and Preventions

- Antimicrobial-Resistance.md
Added Antimicrobial-Resistance preventions
#430
> Added Antimicrobial-Resistance preventions

- DataSources/Fasting.md
- DataSources/Pediatric Health.md
Added article on "Pediatric Health"
Fixes #412 issue
#412 closes
> Pediatric Health

- Polio-Preventions.md
> Added Polio Prevenntion 

- Datasources/Arrhythmia Insights Understanding and Managing Irregular Heartbeats/English.md
> Added "Arrhythmia Insights Understanding and Managing Irregular Heartbeats"

- DataSources/English/Quantum-Computing-in-Drug-Discovery.md
Quantum Computing in Drug Discovery Added
Quantum Computing in Drug Discovery Added
#447
> Quantum Computing in Drug Discovery Added

- DataSources/English/Artificial Intelligence in Diagnostics.md
Artificial Intelligence in Diagnostics Added
#442
> Artificial Intelligence in Diagnostics Added

- Datasources/Oral_diseases_and_prevention.md
Added Create Cystic_Fibrosis
#511
> Added Oral_diseases_and_prevention.

- DataSources/English/Psychosis and Schizophrenia.md
Psychosis and Schizophrenia Added
#426
> Psychosis and Schizophrenia Added

- backend/controllers/usersControllers.js
> --email-fixed

- frontend/src/components/ProfileHeader.tsx
- frontend/src/helper/APIUtils.ts
- frontend/src/navigations/StackNavigation.tsx
- frontend/src/screens/article/ArticleDescriptionScreen.tsx
- frontend/src/screens/article/PreviewScreen.tsx
- frontend/src/screens/auth/LogoutScreen.tsx
- frontend/src/type.ts
> Logout and ArticleScreen Revamp

- frontend/src/screens/HomeScreen.tsx
- frontend/src/store/dataSlice.ts
> --filter--param--bug--fix
